### ISSUE TITLE
Issue on Eclipse : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sqisland.android.recyclerview.MainActivity"

### ISSUE THREAD

**Issue by rahulfhp** [chiuki/android-recyclerview#1]
05-27 14:18:59.051: E/AndroidRuntime(3016):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
05-27 14:18:59.051: E/AndroidRuntime(3016):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
05-27 14:18:59.051: E/AndroidRuntime(3016): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sqisland.android.recyclerview.MainActivity" on path: DexPathList[[zip file "/data/app/com.sqisland.android.recyclerview-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
05-27 14:18:59.051: E/AndroidRuntime(3016):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-27 14:18:59.051: E/AndroidRuntime(3016):     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-27 14:18:59.051: E/AndroidRuntime(3016):     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)

**Comment by lovebdsobuj** [comment]
Use `Android Studio`.
[Android Studio Overview | Android Developers](http://developer.android.com/tools/studio/index.html)

> Android Studio is the official IDE for Android app development, based on IntelliJ IDEA.
