### ISSUE TITLE
Does the AutoFitRecyclerView still work?

### ISSUE THREAD

**Issue by duartebarbosadev** [chiuki/android-recyclerview#4]
Hi
With the latest recyclerview updates on android, everything that was match_parent should go to wrap_content
But I don't know why the AutoFitRecyclerView just dosent work anymore
This is before i update the recyclerview library:
http://imgur.com/j5jZRaU

This is after:
http://imgur.com/cTaffpW

**Comment by chiuki** [comment]
Can you update the recyclerview library on this repository instead of your own? That way we know whether this sample code is broken or not.

**Comment by duartebarbosadev** [comment]
I did it and it still works only adding a very very small space between.
before/after here:http://imgur.com/a/9g1Xy

I figure it out that i had a wrong, my AutoFitRecyclerView was different from yours.
But there is a thing that I can understand and if you helped me it would be great.
My layout is suppost to work like this:
Small phones have this design (working):
http://imgur.com/0FNHCX4

Bigger phones have this design (not working):
http://imgur.com/j5jZRaU

So I updated my AutoFitRecyclerView to yours
and it is like so on smaller/Bigger phones: 
http://imgur.com/JPlO7D9

This was my Previous AutoFitRecyclerView:
http://pastebin.com/vgDp7Zdw

Can you help me?

**Comment by chiuki** [comment]
Closing this issue since the code in this repository still works with the new recyclerview library.
